### ISSUE TITLE
use individual accounts instead of core user

### ISSUE THREAD

**Issue by puja108** [giantswarm/k8scloudconfig#102]
This is a summary of several securiy tickets regarding use of the core user.

1. We should have individual users and not use the core user as a group account, because of IT forensics and audiabitlity https://github.com/giantswarm/vodafone/issues/123
2. We should remove the rights of the core user https://github.com/giantswarm/vodafone/issues/132 https://github.com/giantswarm/vodafone/issues/133 https://github.com/giantswarm/vodafone/issues/134

**Comment by xh3b4sd** [comment]
@kopiczko and I have brainstormed a little bit, because we have to sort the public key injection for the kvm-operator now somehow. I am not happy with the way we are doing it in the aws-operator at the moment so I wanted to move further into the right direction. In the future when a customer requests a guest cluster creation, the public keys should be configured with the request as kubernetesd sees it. Behind the API we will maybe have some sort of public key management. We can maybe allow any user who has granted access to the k8s API also access to the KVM-pods/AWS-instances. We could also provide some admin configuration independent from the k8s API certificates. I think these are details based on the user requirements. No biggy. 

In the long run we want to have a TPO issued for each public key, like we have it for certificates of internal services like etcd. There will be a public key operator creating secrets for the actual public keys. The public key operator can also leverage Vault. The separation of certificate operator and public key operator is good because the data is quiet different as well as the use case and place where it is used at the end. The public keys will be configured via cloud config, or ignition in case we upgrade to it.

**Comment by puja108** [comment]
@teemow mentioned we could use the SSH backend of Vault.

Re access for users: let's not mix the layers (VM, K8s), but we can talk about user mgmt story other places.

**Comment by xh3b4sd** [comment]
> Re access for users: let's not mix the layers (VM, K8s)

+1, this is why we want to have different TPRs and different operators for it.

**Comment by calvix** [comment]
solved in https://github.com/giantswarm/k8scloudconfig/issues/10
