### ISSUE TITLE
kube-dns isn't working

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/k8scloudconfig#41]
Towards giantswarm/giantswarm#1388

kube-dns doesn't work properly, the pod fails constantly.

We need to debug this.

**Comment by puja108** [comment]
If we're running into a general bug with this version, we should consider upgrading KubeDNS, we're quite behind (1.9 vs 1.14.1) anyway there, but newer versions might also need other adjustments, so there'd be a risk.

**Comment by puja108** [comment]
the problem seems to be following:
```reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: Get https://api.7pw6d.g8s.eu-west-1.adidas.aws.giantswarm.io/api/v1/services?resourceVersion=0: dial tcp: lookup api.7pw6d.g8s.eu-west-1.adidas.aws.giantswarm.io on 10.0.0.2:53: read udp 192.168.47.193:60928->10.0.0.2:53: i/o timeout```

`10.0.0.2` is Amazon DNS (route53 I guess) and seems to be timing out. This happens on all nodes and is not flakiness.

I found a similar issue here:
https://github.com/kubernetes/kubernetes/issues/20893
and here:
https://github.com/kubernetes/kubernetes/issues/15932

This suggests we might need to change our ip ranges, I tired changing service ip range from `10.0.3.0/24` to `172.31.0.0/24` and restarted all components, but nothing happened, the cluster ip of e.g. kubernetes service stood in the old range, not sure why.

**Comment by calvix** [comment]
is pod network connection working all right in all directions  ( pod -> internet, pod -> pod, pod -> k8s master) ?

**Comment by puja108** [comment]
pod->k8s master seems to be working, other things I have not tested, partly because of: https://github.com/giantswarm/k8scloudconfig/issues/89

**Comment by calvix** [comment]
I just saw https://github.com/giantswarm/k8scloudconfig/pull/90 this may be reason why this was not working.

also check if `leader-elector` is working fine 

all components of calico needs to run fine or else kubedns wont work.

**Comment by rossf7** [comment]
Good spot and that makes sense. I'll launch a new cluster once the fix for #90 is deployed.

**Comment by puja108** [comment]
kubedns seems to be working now, I cannot test because of #89 but the logs look like they should, will close for now
